class_name ActionLocalization
extends RefCounted

const DEFAULT_LOCALE := "en"
const SUPPORTED_LOCALES := ["en", "zh_TW", "ja", "ko"]
const LOCALE_NAMES := {
	"en": "English",
	"zh_TW": "繁體中文",
	"ja": "日本語",
	"ko": "한국어",
}

const STRINGS := {
	"en": {
		"open": "Open", "recover": "Recover", "import": "Import", "save": "Save", "export": "Export",
		"undo": "Undo", "redo": "Redo", "step_back": "Step -", "play": "Play", "pause": "Pause",
		"step_forward": "Step +", "reset": "Reset", "compare_on": "A/B On", "compare_off": "A/B Off",
		"project": "PROJECT", "open_2d_sample": "Open the redistributable 2D spritesheet demo", "open_3d_sample": "Open the redistributable CC0 FBX motion demo", "sample_2d_short": "2D Sprite Demo", "sample_3d_short": "3D FBX Demo",
		"no_comparison": "No comparison", "compare_with": "COMPARE WITH", "no_compare_take": "No other Take", "tip_compare_take": "Choose any other Take as the synchronized comparison", "comparison_changed": "Comparing %s with %s.", "duplicate_take": "Duplicate Take", "language": "Language",
		"alpha_status_tip": "Early open-source build. Save and export often.", "workspace_loading": "Loading rehearsal workspace…", "workspace_context": "%s  ·  %s  ·  %d takes", "dimension_tip": "%s action project; dimensions cannot be mixed", "samples": "SAMPLES", "rehearsal": "REHEARSAL",
		"jump_to_difference": "Go to difference", "tip_jump_to_difference": "Move the playhead to the first semantic difference between the two takes", "jumped_to_difference": "Moved to the first A/B difference at tick %d.",
		"ready": "Ready", "actions": "Actions", "takes_count": "Takes (%d)", "actors": "Actors", "assets_count": "Assets (%d)",
		"first_difference": "%s vs %s · first difference %s · duration %+d ticks", "tick_value": "tick %d", "none": "none",
		"imported_asset": "Imported %s into the local project.%s", "mixamo_summary": " Mixamo rig: %d skeleton(s), %d clip(s): %s.",
		"mixamo_no_animation": " FBX imported, but no animation clip was found. In Mixamo, download with Skin and FBX Binary.",
		"save_before_import": "Save this workspace as an .adproject before importing, so copied assets stay project-relative.",
		"unsupported_asset": "Unsupported asset type .%s. Use PNG, WebP, WAV, OGG, GLB, glTF, or Mixamo FBX.",
		"asset_missing": "Asset no longer exists: %s",
		"language_changed": "Language changed to %s. The choice is saved on this device.",
		"performer": "PERFORMER", "target": "TARGET", "hitbox": "HITBOX",
		"hit_help": "Left click active hitbox: HIT  ·  Right click: BLOCK", "tracks": "TRACKS",
		"timeline": "TIMELINE", "selection_none": "Nothing selected", "selection_event": "%s selected at tick %d", "selection_track": "%s track selected", "timeline_empty": "No tracks yet. Choose an event type and add a track.",
		"new_event_type": "New event", "add_event": "Add at playhead", "add_track": "Add track", "delete_event": "Delete event", "delete_track": "Delete track", "timeline_authoring_hint": "Timeline focused: ↑↓ tracks · ←→ events · Delete is undoable",
		"tip_add_event": "Add this event type at the current tick; a compatible track is created when needed", "tip_add_track": "Add an empty track for this event type", "tip_delete_event": "Delete the selected event · Delete", "tip_delete_track": "Delete the selected track and its events · Delete",
		"inspector": "INSPECTOR", "inspector_empty": "Select an event in the timeline to edit its actor, timing, type, and payload. Track selection enables track actions without exposing inactive event fields.", "primary_take": "PRIMARY TAKE", "comparison_take": "COMPARISON TAKE",
		"no_event": "No event selected", "event_id": "Event ID", "type": "Type", "actor_id": "Actor", "start_tick": "Start tick",
		"end_tick": "End tick", "payload_json": "Payload JSON", "apply_event": "Apply event changes",
		"inspector_hint": "Type, actor, timing, and payload edits update this take. Export the action to keep them.",
		"no_actor": "No actor", "missing_actor": "Missing actor · %s", "unknown_event_type": "Unknown type · %s",
		"event_type_animation": "Animation", "event_type_window": "Combat window", "event_type_hitbox": "Hitbox", "event_type_hurtbox": "Hurtbox", "event_type_motion": "Motion", "event_type_feel": "Feel", "event_type_audio": "Audio", "event_type_vfx": "VFX", "event_type_camera": "Camera", "event_type_game_event": "Game event", "event_type_note": "Note",
		"payload_invalid": "Payload must be a valid JSON object. Your previous event data is unchanged.",
		"event_contract_invalid": "This edit would make the ActionSpec invalid: %s Your previous event data is unchanged.",
		"timing_out_of_range": "Event timing must stay between tick 0 and %d. The previous event is unchanged.",
		"model_parse_failed": "%s could not be read as a 3D model. The file was not added. %s",
		"open_failed": "Could not open the file: %s", "project_opened": "Opened project %s%s", "project_source_missing": " · original action missing; using embedded recovery copy",
		"action_opened": "Opened %s%s", "compatibility_warnings": " · %d compatibility warning(s)", "take_duplicated": "Duplicated %s as %s with independent IDs.",
		"undo_duplicate_take": "Duplicate take", "take_duplication_undone": "Removed duplicated take %s. Redo is available.",
		"event_updated": "Updated %s. Export the action to keep this change.", "outcome_reported": "%s rehearsal reported %s for %s; matching branches will execute on their scheduled tick.",
		"track_selected": "Selected track %s.", "track_added": "Added %s track.", "event_added": "Added %s at tick %d.", "event_deleted": "Deleted event %s. Undo is available.", "track_deleted": "Deleted track %s and %d event(s). Undo is available.",
		"select_event_to_delete": "Select an event before deleting it.", "select_track_to_delete": "Select a track label before deleting it.", "authoring_undone": "Undid the timeline structure change.", "undo_add_track": "Add track", "undo_add_event": "Add event", "undo_delete_event": "Delete event", "undo_delete_track": "Delete track",
		"branch_taken": "%s took branch %s to %s.", "saved_project": "Saved project%s.", "saved_backup": " with recovery backup", "action_exported": "Exported action to %s",
		"no_recovery": "No recovery action exists yet. Action Director creates one every 30 seconds.", "recovered": "Recovered the most recent autosave. Export it to a project path to keep it.",
		"payload_apply_invalid": "Payload JSON is invalid. Correct the payload before applying changes.",
		"tip_open": "Open an .action.json or .adproject file", "tip_recover": "Open the most recent crash-recovery action", "tip_import": "Import PNG, WebP, audio, GLB, glTF, or Mixamo FBX", "tip_save": "Save workspace as .adproject", "tip_export": "Export versionable .action.json",
		"tip_undo": "Undo · Ctrl+Z", "tip_redo": "Redo · Ctrl+Y", "tip_step_back": "Previous tick · [,]", "tip_play": "Play or pause · Space", "tip_step_forward": "Next tick · [.]", "tip_reset": "Return to tick zero · R", "tip_compare_on": "Toggle A/B comparison · C", "tip_duplicate_take": "Create an independent copy with new stable IDs", "animation_clips": "Animation clips: %s",
		"project_missing": "Project file does not exist: %s", "project_cannot_open": "Project file could not be opened: %s", "project_damaged": "Project file is damaged. The original file was not changed.", "project_no_schema": "Project file has no schema version.", "project_no_action": "Project has no embedded ActionSpec. Reopen the original action and save this workspace again.", "project_action_invalid": "Embedded ActionSpec is invalid; the project was not modified.",
		"project_temp_failed": "Could not create a temporary project file.", "project_replace_failed": "Could not replace the project safely. Temporary data remains at %s.", "asset_unsupported": "Unsupported asset type .%s. Use PNG, WebP, WAV, OGG, GLB, glTF, or Mixamo FBX.", "asset_not_found": "Asset no longer exists: %s", "asset_copy_failed": "Could not copy the asset into the project.",
		"tutorial": "Tutorial", "tip_tutorial": "Open the in-app tutorials and workflow reference", "tutorial_title": "Action Director Tutorial Center", "tutorial_skip": "Skip for now", "tutorial_close": "Close", "tutorial_mark_done": "Mark chapter complete", "tutorial_mark_undone": "Mark as incomplete", "tutorial_open_2d": "Open 2D sample and practice", "tutorial_open_3d": "Open 3D sample and practice", "tutorial_progress": "%d of %d chapters complete", "manual": "Full guide", "tip_manual": "Open the searchable offline user guide", "manual_title": "Action Director Complete User Guide", "manual_search": "Search this guide (Ctrl/Cmd+F)", "manual_next": "Find next", "manual_found": "Found", "manual_not_found": "No match",
	},
	"zh_TW": {
		"open": "開啟", "recover": "復原", "import": "匯入素材", "save": "儲存", "export": "匯出",
		"undo": "復原操作", "redo": "重做", "step_back": "前一格", "play": "播放", "pause": "暫停",
		"step_forward": "下一格", "reset": "重設", "compare_on": "A/B 開啟", "compare_off": "A/B 關閉",
		"project": "專案", "open_2d_sample": "開啟可再散布的 2D 逐格動作範例", "open_3d_sample": "開啟可再散布的 CC0 FBX 動作範例", "sample_2d_short": "2D 逐格範例", "sample_3d_short": "3D FBX 範例",
		"no_comparison": "尚無比較", "compare_with": "比較對象", "no_compare_take": "沒有其他 Take", "tip_compare_take": "指定任一其他 Take 作為同步比較版本", "comparison_changed": "正在比較 %s 與 %s。", "duplicate_take": "複製 Take", "language": "語言",
		"alpha_status_tip": "早期開源版本；請定期儲存與匯出。", "workspace_loading": "正在載入預演工作區…", "workspace_context": "%s  ·  %s  ·  %d 個 Take", "dimension_tip": "%s 動作專案；同一專案不混用維度", "samples": "範例", "rehearsal": "預演",
		"jump_to_difference": "跳到差異", "tip_jump_to_difference": "將播放頭移到兩個 Take 第一個語意差異", "jumped_to_difference": "已移到第 %d tick 的首個 A/B 差異。",
		"ready": "就緒", "actions": "動作", "takes_count": "Take（%d）", "actors": "演員", "assets_count": "素材（%d）",
		"first_difference": "%s 對 %s · 首次差異 %s · 長度差 %+d ticks", "tick_value": "第 %d tick", "none": "無",
		"imported_asset": "已將 %s 匯入本機專案。%s", "mixamo_summary": " Mixamo 骨架：%d 組，動畫：%d 段（%s）。",
		"mixamo_no_animation": " FBX 已匯入，但找不到動畫片段；請在 Mixamo 以 Skin 與 FBX Binary 重新下載。",
		"save_before_import": "請先把工作區存成 .adproject，再匯入素材，才能維持專案相對路徑。",
		"unsupported_asset": "不支援 .%s；請使用 PNG、WebP、WAV、OGG、GLB、glTF 或 Mixamo FBX。",
		"asset_missing": "素材已不存在：%s",
		"language_changed": "介面已切換為%s，並儲存在這台裝置。",
		"performer": "演員", "target": "目標", "hitbox": "攻擊框",
		"hit_help": "左鍵回報命中 · 右鍵回報格擋", "tracks": "軌道",
		"timeline": "時間軸", "selection_none": "尚未選取", "selection_event": "已選%s · 第 %d tick", "selection_track": "已選取%s軌道", "timeline_empty": "尚無軌道；請選擇事件類型後新增軌道。",
		"new_event_type": "新增事件", "add_event": "加到播放頭", "add_track": "新增軌道", "delete_event": "刪除事件", "delete_track": "刪除軌道", "timeline_authoring_hint": "聚焦時間軸：↑↓ 選軌道 · ←→ 選事件 · 刪除可復原",
		"tip_add_event": "在目前 tick 加入這種事件；需要時會自動建立相容軌道", "tip_add_track": "為這種事件新增空白軌道", "tip_delete_event": "刪除已選事件 · Delete", "tip_delete_track": "刪除已選軌道及其中事件 · Delete",
		"inspector": "檢視器", "inspector_empty": "請在時間軸選取事件，再編輯演員、時間、類型與 Payload。選取軌道時只會啟用軌道操作，不顯示無效事件欄位。", "primary_take": "主要 TAKE", "comparison_take": "比較 TAKE",
		"no_event": "尚未選取事件", "event_id": "事件 ID", "type": "類型", "actor_id": "演員", "start_tick": "開始 tick",
		"end_tick": "結束 tick", "payload_json": "Payload JSON", "apply_event": "套用事件修改",
		"inspector_hint": "類型、演員、時間與 Payload 會更新目前 Take；請匯出動作以保留修改。",
		"no_actor": "不指定演員", "missing_actor": "找不到演員 · %s", "unknown_event_type": "未知類型 · %s",
		"event_type_animation": "動畫", "event_type_window": "戰鬥窗口", "event_type_hitbox": "攻擊框", "event_type_hurtbox": "受擊框", "event_type_motion": "位移", "event_type_feel": "手感", "event_type_audio": "音效", "event_type_vfx": "VFX", "event_type_camera": "鏡頭", "event_type_game_event": "遊戲事件", "event_type_note": "備註",
		"payload_invalid": "Payload 必須是有效 JSON 物件；原事件資料未被修改。",
		"event_contract_invalid": "此修改會使 ActionSpec 無效：%s 原事件資料未被修改。",
		"timing_out_of_range": "事件時間必須介於第 0 至 %d tick；原事件未被修改。",
		"model_parse_failed": "無法將 %s 讀取為 3D 模型，因此未加入專案。%s",
		"open_failed": "無法開啟檔案：%s", "project_opened": "已開啟專案 %s%s", "project_source_missing": " · 原始動作已遺失，改用專案內嵌復原副本",
		"action_opened": "已開啟 %s%s", "compatibility_warnings": " · %d 個相容性警告", "take_duplicated": "已將 %s 複製為 %s，並建立獨立 ID。",
		"undo_duplicate_take": "複製 Take", "take_duplication_undone": "已移除複製的 Take %s，可使用重做恢復。",
		"event_updated": "已更新 %s；請匯出動作以保留修改。", "outcome_reported": "%s 預演回報 %s（%s）；符合的分支會在排定 tick 執行。",
		"track_selected": "已選取軌道 %s。", "track_added": "已新增 %s 軌道。", "event_added": "已新增%s於第 %d tick。", "event_deleted": "已刪除事件 %s，可使用復原操作。", "track_deleted": "已刪除軌道 %s 及其中 %d 個事件，可使用復原操作。",
		"select_event_to_delete": "請先選取要刪除的事件。", "select_track_to_delete": "請先點選要刪除的軌道名稱。", "authoring_undone": "已復原時間軸結構修改。", "undo_add_track": "新增軌道", "undo_add_event": "新增事件", "undo_delete_event": "刪除事件", "undo_delete_track": "刪除軌道",
		"branch_taken": "%s 已走分支 %s 至 %s。", "saved_project": "專案已儲存%s。", "saved_backup": "，並建立復原備份", "action_exported": "動作已匯出至 %s",
		"no_recovery": "目前沒有復原動作；動作導演台每 30 秒建立一次。", "recovered": "已復原最近的自動存檔；請匯出到專案路徑以保留。",
		"payload_apply_invalid": "Payload JSON 無效；請修正後再套用。",
		"tip_open": "開啟 .action.json 或 .adproject", "tip_recover": "開啟最近的崩潰復原動作", "tip_import": "匯入 PNG、WebP、音訊、GLB、glTF 或 Mixamo FBX", "tip_save": "將工作區存為 .adproject", "tip_export": "匯出可版本控制的 .action.json",
		"tip_undo": "復原 · Ctrl+Z", "tip_redo": "重做 · Ctrl+Y", "tip_step_back": "前一 tick · [,]", "tip_play": "播放或暫停 · Space", "tip_step_forward": "下一 tick · [.]", "tip_reset": "回到 tick 0 · R", "tip_compare_on": "切換 A/B 比較 · C", "tip_duplicate_take": "建立完整獨立副本與新 ID", "animation_clips": "動畫片段：%s",
		"project_missing": "專案檔不存在：%s", "project_cannot_open": "無法開啟專案檔：%s", "project_damaged": "專案檔已損壞；原始檔案未被修改。", "project_no_schema": "專案檔缺少 schema 版本。", "project_no_action": "專案沒有內嵌 ActionSpec；請重新開啟原始動作並儲存工作區。", "project_action_invalid": "內嵌 ActionSpec 無效；專案未被修改。",
		"project_temp_failed": "無法建立暫存專案檔。", "project_replace_failed": "無法安全替換專案；暫存資料保留於 %s。", "asset_unsupported": "不支援 .%s；請使用 PNG、WebP、WAV、OGG、GLB、glTF 或 Mixamo FBX。", "asset_not_found": "素材已不存在：%s", "asset_copy_failed": "無法將素材複製進專案。",
		"tutorial": "教學", "tip_tutorial": "開啟程式內教學與操作流程參考", "tutorial_title": "動作導演台教學中心", "tutorial_skip": "暫時跳過", "tutorial_close": "關閉", "tutorial_mark_done": "標記本章完成", "tutorial_mark_undone": "改為未完成", "tutorial_open_2d": "開啟 2D 範例並練習", "tutorial_open_3d": "開啟 3D 範例並練習", "tutorial_progress": "已完成 %d／%d 章", "manual": "完整手冊", "tip_manual": "開啟可搜尋的離線完整使用手冊", "manual_title": "動作導演台完整使用手冊", "manual_search": "搜尋本手冊（Ctrl/Cmd+F）", "manual_next": "找下一個", "manual_found": "已找到", "manual_not_found": "找不到",
	},
	"ja": {
		"open": "開く", "recover": "復元", "import": "素材を読込", "save": "保存", "export": "書き出し",
		"undo": "元に戻す", "redo": "やり直す", "step_back": "前フレーム", "play": "再生", "pause": "一時停止",
		"step_forward": "次フレーム", "reset": "リセット", "compare_on": "A/B オン", "compare_off": "A/B オフ",
		"project": "プロジェクト", "open_2d_sample": "再配布可能な2Dスプライトデモを開く", "open_3d_sample": "再配布可能なCC0 FBXモーションデモを開く", "sample_2d_short": "2Dスプライト", "sample_3d_short": "3D FBXデモ",
		"no_comparison": "比較なし", "compare_with": "比較対象", "no_compare_take": "他のTakeなし", "tip_compare_take": "同期比較する別のTakeを選択", "comparison_changed": "%s と %s を比較しています。", "duplicate_take": "Takeを複製", "language": "言語",
		"alpha_status_tip": "初期オープンソース版です。こまめに保存・書き出ししてください。", "workspace_loading": "リハーサルワークスペースを読み込み中…", "workspace_context": "%s  ·  %s  ·  %d Take", "dimension_tip": "%s アクションプロジェクト（次元の混在はできません）", "samples": "サンプル", "rehearsal": "リハーサル",
		"jump_to_difference": "差分へ移動", "tip_jump_to_difference": "2つのTakeで最初の意味的な差分へ再生ヘッドを移動", "jumped_to_difference": "最初のA/B差分（tick %d）へ移動しました。",
		"ready": "準備完了", "actions": "アクション", "takes_count": "Take（%d）", "actors": "アクター", "assets_count": "素材（%d）",
		"first_difference": "%s 対 %s · 最初の差分 %s · 長さ %+d ticks", "tick_value": "tick %d", "none": "なし",
		"imported_asset": "%s をローカルプロジェクトに読み込みました。%s", "mixamo_summary": " Mixamoリグ：%d、クリップ：%d（%s）。",
		"mixamo_no_animation": " FBXは読み込まれましたが、アニメーションがありません。MixamoでSkin付きFBX Binaryを選んでください。",
		"save_before_import": "素材を相対パスで保持するため、先に.adprojectとして保存してください。",
		"unsupported_asset": ".%s は未対応です。PNG、WebP、WAV、OGG、GLB、glTF、Mixamo FBXを使用してください。",
		"asset_missing": "素材が見つかりません：%s",
		"language_changed": "表示言語を%sに変更し、この端末に保存しました。",
		"performer": "演者", "target": "ターゲット", "hitbox": "ヒットボックス", "hit_help": "左クリック：ヒット · 右クリック：ガード",
		"timeline": "タイムライン", "selection_none": "未選択", "selection_event": "%sをtick %dで選択", "selection_track": "%sトラックを選択", "timeline_empty": "トラックがありません。種類を選び、トラックを追加してください。",
		"tracks": "トラック", "new_event_type": "新規イベント", "add_event": "再生ヘッドに追加", "add_track": "トラック追加", "delete_event": "イベント削除", "delete_track": "トラック削除", "timeline_authoring_hint": "タイムラインにフォーカス：↑↓ トラック · ←→ イベント · 削除は元に戻せます",
		"tip_add_event": "現在のtickにこの種類のイベントを追加し、必要なら対応トラックも作成します", "tip_add_track": "このイベント種類用の空トラックを追加します", "tip_delete_event": "選択イベントを削除 · Delete", "tip_delete_track": "選択トラックとイベントを削除 · Delete",
		"inspector": "インスペクター", "inspector_empty": "タイムラインでイベントを選び、アクター、タイミング、種類、Payloadを編集します。トラック選択中は無効なイベント欄を表示しません。", "primary_take": "プライマリ TAKE", "comparison_take": "比較 TAKE",
		"no_event": "イベント未選択", "event_id": "イベントID", "type": "種類", "actor_id": "アクター", "start_tick": "開始tick",
		"end_tick": "終了tick", "payload_json": "Payload JSON", "apply_event": "イベント変更を適用",
		"inspector_hint": "種類、アクター、時間、Payloadの変更は現在のTakeに反映されます。保持するには書き出してください。",
		"no_actor": "アクターなし", "missing_actor": "不明なアクター · %s", "unknown_event_type": "不明な種類 · %s",
		"event_type_animation": "アニメーション", "event_type_window": "戦闘ウィンドウ", "event_type_hitbox": "ヒットボックス", "event_type_hurtbox": "ハートボックス", "event_type_motion": "移動", "event_type_feel": "手触り", "event_type_audio": "オーディオ", "event_type_vfx": "VFX", "event_type_camera": "カメラ", "event_type_game_event": "ゲームイベント", "event_type_note": "メモ",
		"payload_invalid": "Payloadは有効なJSONオブジェクトが必要です。元のデータは変更されていません。",
		"event_contract_invalid": "この変更ではActionSpecが無効になります：%s 元のイベントデータは変更されていません。",
		"timing_out_of_range": "イベント時刻はtick 0から%dの範囲にしてください。以前のEventは変更されていません。",
		"model_parse_failed": "%s を3Dモデルとして読み込めなかったため、追加しませんでした。%s",
		"open_failed": "ファイルを開けません：%s", "project_opened": "プロジェクト %s を開きました%s", "project_source_missing": " · 元アクションがないため埋め込み復元コピーを使用",
		"action_opened": "%s を開きました%s", "compatibility_warnings": " · 互換性警告 %d 件", "take_duplicated": "%s を %s として独立IDで複製しました。",
		"undo_duplicate_take": "Takeを複製", "take_duplication_undone": "複製Take %sを削除しました。やり直しできます。",
		"event_updated": "%s を更新しました。保持するには書き出してください。", "outcome_reported": "%s 側が %s（%s）を報告しました。分岐は予定tickで実行されます。",
		"track_selected": "トラック %s を選択しました。", "track_added": "%s トラックを追加しました。", "event_added": "%s をtick %dに追加しました。", "event_deleted": "イベント %s を削除しました。元に戻せます。", "track_deleted": "トラック %s とイベント%d件を削除しました。元に戻せます。",
		"select_event_to_delete": "削除するイベントを選択してください。", "select_track_to_delete": "削除するトラック名を選択してください。", "authoring_undone": "タイムライン構造の変更を元に戻しました。", "undo_add_track": "トラック追加", "undo_add_event": "イベント追加", "undo_delete_event": "イベント削除", "undo_delete_track": "トラック削除",
		"branch_taken": "%s 側が分岐 %s から %s へ進みました。", "saved_project": "プロジェクトを保存しました%s。", "saved_backup": "（復元バックアップあり）", "action_exported": "%s に書き出しました",
		"no_recovery": "復元データはまだありません。30秒ごとに作成されます。", "recovered": "最新の自動保存を復元しました。保持するにはプロジェクトへ書き出してください。",
		"payload_apply_invalid": "Payload JSONが無効です。修正してから適用してください。",
		"tip_open": ".action.json / .adprojectを開く", "tip_recover": "最新のクラッシュ復元を開く", "tip_import": "PNG、WebP、音声、GLB、glTF、Mixamo FBXを読込", "tip_save": ".adprojectとして保存", "tip_export": ".action.jsonを書き出す",
		"tip_undo": "元に戻す · Ctrl+Z", "tip_redo": "やり直す · Ctrl+Y", "tip_step_back": "前のtick · [,]", "tip_play": "再生 / 一時停止 · Space", "tip_step_forward": "次のtick · [.]", "tip_reset": "tick 0へ戻る · R", "tip_compare_on": "A/B比較切替 · C", "tip_duplicate_take": "新しいIDで独立コピーを作成", "animation_clips": "アニメーションクリップ：%s",
		"project_missing": "プロジェクトファイルがありません：%s", "project_cannot_open": "プロジェクトファイルを開けません：%s", "project_damaged": "プロジェクトファイルが破損しています。元ファイルは変更されていません。", "project_no_schema": "プロジェクトにschemaバージョンがありません。", "project_no_action": "埋め込みActionSpecがありません。元アクションを開き直して保存してください。", "project_action_invalid": "埋め込みActionSpecが無効です。プロジェクトは変更されていません。",
		"project_temp_failed": "一時プロジェクトファイルを作成できません。", "project_replace_failed": "安全に置換できません。一時データは %s に残っています。", "asset_unsupported": ".%s は未対応です。PNG、WebP、WAV、OGG、GLB、glTF、Mixamo FBXを使用してください。", "asset_not_found": "素材が見つかりません：%s", "asset_copy_failed": "素材をプロジェクトへコピーできませんでした。",
		"tutorial": "チュートリアル", "tip_tutorial": "アプリ内チュートリアルとワークフロー資料を開く", "tutorial_title": "Action Director チュートリアル", "tutorial_skip": "今はスキップ", "tutorial_close": "閉じる", "tutorial_mark_done": "この章を完了", "tutorial_mark_undone": "未完了に戻す", "tutorial_open_2d": "2Dサンプルで練習", "tutorial_open_3d": "3Dサンプルで練習", "tutorial_progress": "%d / %d章 完了", "manual": "詳細ガイド", "tip_manual": "検索可能なオフラインユーザーガイドを開く", "manual_title": "Action Director 詳細ユーザーガイド", "manual_search": "ガイドを検索（Ctrl/Cmd+F）", "manual_next": "次を検索", "manual_found": "見つかりました", "manual_not_found": "一致なし",
	},
	"ko": {
		"open": "열기", "recover": "복구", "import": "에셋 가져오기", "save": "저장", "export": "내보내기",
		"undo": "실행 취소", "redo": "다시 실행", "step_back": "이전 프레임", "play": "재생", "pause": "일시정지",
		"step_forward": "다음 프레임", "reset": "초기화", "compare_on": "A/B 켜기", "compare_off": "A/B 끄기",
		"project": "프로젝트", "open_2d_sample": "재배포 가능한 2D 스프라이트 데모 열기", "open_3d_sample": "재배포 가능한 CC0 FBX 모션 데모 열기", "sample_2d_short": "2D 스프라이트", "sample_3d_short": "3D FBX 데모",
		"no_comparison": "비교 없음", "compare_with": "비교 대상", "no_compare_take": "다른 Take 없음", "tip_compare_take": "동기화해 비교할 다른 Take를 선택하세요", "comparison_changed": "%s와(과) %s 비교 중.", "duplicate_take": "Take 복제", "language": "언어",
		"alpha_status_tip": "초기 오픈소스 빌드입니다. 자주 저장하고 내보내세요.", "workspace_loading": "리허설 작업 공간 로드 중…", "workspace_context": "%s  ·  %s  ·  Take %d개", "dimension_tip": "%s 액션 프로젝트; 차원을 혼합할 수 없습니다", "samples": "샘플", "rehearsal": "리허설",
		"jump_to_difference": "차이로 이동", "tip_jump_to_difference": "두 Take의 첫 의미적 차이로 재생 헤드를 이동", "jumped_to_difference": "tick %d의 첫 A/B 차이로 이동했습니다.",
		"ready": "준비됨", "actions": "액션", "takes_count": "Take (%d)", "actors": "액터", "assets_count": "에셋 (%d)",
		"first_difference": "%s 대 %s · 첫 차이 %s · 길이 %+d ticks", "tick_value": "tick %d", "none": "없음",
		"imported_asset": "%s 에셋을 로컬 프로젝트로 가져왔습니다.%s", "mixamo_summary": " Mixamo 리그: %d개, 클립: %d개 (%s).",
		"mixamo_no_animation": " FBX를 가져왔지만 애니메이션을 찾지 못했습니다. Mixamo에서 Skin 포함 FBX Binary로 받으세요.",
		"save_before_import": "상대 경로를 유지하려면 먼저 .adproject로 저장하세요.",
		"unsupported_asset": ".%s 형식은 지원하지 않습니다. PNG, WebP, WAV, OGG, GLB, glTF 또는 Mixamo FBX를 사용하세요.",
		"asset_missing": "에셋이 없습니다: %s",
		"language_changed": "언어를 %s(으)로 변경하고 이 기기에 저장했습니다.",
		"performer": "연기자", "target": "대상", "hitbox": "히트박스", "hit_help": "왼쪽 클릭: HIT · 오른쪽 클릭: BLOCK",
		"timeline": "타임라인", "selection_none": "선택 없음", "selection_event": "%s 선택 · tick %d", "selection_track": "%s 트랙 선택", "timeline_empty": "트랙이 없습니다. 이벤트 유형을 고르고 트랙을 추가하세요.",
		"tracks": "트랙", "new_event_type": "새 이벤트", "add_event": "재생 헤드에 추가", "add_track": "트랙 추가", "delete_event": "이벤트 삭제", "delete_track": "트랙 삭제", "timeline_authoring_hint": "타임라인 포커스: ↑↓ 트랙 · ←→ 이벤트 · 삭제는 실행 취소 가능",
		"tip_add_event": "현재 tick에 이 유형의 이벤트를 추가하고 필요하면 호환 트랙을 만듭니다", "tip_add_track": "이 이벤트 유형을 위한 빈 트랙을 추가합니다", "tip_delete_event": "선택한 이벤트 삭제 · Delete", "tip_delete_track": "선택한 트랙과 이벤트 삭제 · Delete",
		"inspector": "인스펙터", "inspector_empty": "타임라인에서 이벤트를 선택한 뒤 액터, 타이밍, 유형, Payload를 편집하세요. 트랙 선택 시 비활성 이벤트 필드는 표시하지 않습니다.", "primary_take": "기준 TAKE", "comparison_take": "비교 TAKE",
		"no_event": "선택된 이벤트 없음", "event_id": "이벤트 ID", "type": "유형", "actor_id": "액터", "start_tick": "시작 tick",
		"end_tick": "종료 tick", "payload_json": "Payload JSON", "apply_event": "이벤트 변경 적용",
		"inspector_hint": "유형, 액터, 시간, Payload 변경은 현재 Take에 반영됩니다. 유지하려면 액션을 내보내세요.",
		"no_actor": "액터 없음", "missing_actor": "누락된 액터 · %s", "unknown_event_type": "알 수 없는 유형 · %s",
		"event_type_animation": "애니메이션", "event_type_window": "전투 윈도우", "event_type_hitbox": "히트박스", "event_type_hurtbox": "허트박스", "event_type_motion": "이동", "event_type_feel": "타격감", "event_type_audio": "오디오", "event_type_vfx": "VFX", "event_type_camera": "카메라", "event_type_game_event": "게임 이벤트", "event_type_note": "메모",
		"payload_invalid": "Payload는 유효한 JSON 객체여야 합니다. 이전 데이터는 변경되지 않았습니다.",
		"event_contract_invalid": "이 변경은 ActionSpec을 유효하지 않게 만듭니다: %s 기존 이벤트 데이터는 변경되지 않았습니다.",
		"timing_out_of_range": "이벤트 시간은 tick 0부터 %d 사이여야 합니다. 기존 이벤트는 변경되지 않았습니다.",
		"model_parse_failed": "%s 파일을 3D 모델로 읽지 못해 추가하지 않았습니다. %s",
		"open_failed": "파일을 열 수 없습니다: %s", "project_opened": "%s 프로젝트를 열었습니다%s", "project_source_missing": " · 원본 액션이 없어 내장 복구본 사용",
		"action_opened": "%s을(를) 열었습니다%s", "compatibility_warnings": " · 호환성 경고 %d개", "take_duplicated": "%s을(를) %s(으)로 독립 ID와 함께 복제했습니다.",
		"undo_duplicate_take": "Take 복제", "take_duplication_undone": "복제한 Take %s을(를) 제거했습니다. 다시 실행할 수 있습니다.",
		"event_updated": "%s을(를) 수정했습니다. 유지하려면 액션을 내보내세요.", "outcome_reported": "%s 리허설이 %s (%s)을 보고했습니다. 분기는 예정 tick에 실행됩니다.",
		"track_selected": "%s 트랙을 선택했습니다.", "track_added": "%s 트랙을 추가했습니다.", "event_added": "%s 이벤트를 tick %d에 추가했습니다.", "event_deleted": "%s 이벤트를 삭제했습니다. 실행 취소할 수 있습니다.", "track_deleted": "%s 트랙과 이벤트 %d개를 삭제했습니다. 실행 취소할 수 있습니다.",
		"select_event_to_delete": "삭제할 이벤트를 먼저 선택하세요.", "select_track_to_delete": "삭제할 트랙 이름을 먼저 선택하세요.", "authoring_undone": "타임라인 구조 변경을 실행 취소했습니다.", "undo_add_track": "트랙 추가", "undo_add_event": "이벤트 추가", "undo_delete_event": "이벤트 삭제", "undo_delete_track": "트랙 삭제",
		"branch_taken": "%s이(가) 분기 %s에서 %s(으)로 이동했습니다.", "saved_project": "프로젝트를 저장했습니다%s.", "saved_backup": " (복구 백업 포함)", "action_exported": "%s 위치로 액션을 내보냈습니다",
		"no_recovery": "복구 액션이 아직 없습니다. 30초마다 생성됩니다.", "recovered": "최근 자동 저장을 복구했습니다. 유지하려면 프로젝트 경로로 내보내세요.",
		"payload_apply_invalid": "Payload JSON이 올바르지 않습니다. 수정한 뒤 적용하세요.",
		"tip_open": ".action.json 또는 .adproject 열기", "tip_recover": "최근 충돌 복구 액션 열기", "tip_import": "PNG, WebP, 오디오, GLB, glTF, Mixamo FBX 가져오기", "tip_save": ".adproject로 저장", "tip_export": ".action.json 내보내기",
		"tip_undo": "실행 취소 · Ctrl+Z", "tip_redo": "다시 실행 · Ctrl+Y", "tip_step_back": "이전 tick · [,]", "tip_play": "재생/일시정지 · Space", "tip_step_forward": "다음 tick · [.]", "tip_reset": "tick 0으로 · R", "tip_compare_on": "A/B 비교 전환 · C", "tip_duplicate_take": "새 ID로 독립 복사본 생성", "animation_clips": "애니메이션 클립: %s",
		"project_missing": "프로젝트 파일이 없습니다: %s", "project_cannot_open": "프로젝트 파일을 열 수 없습니다: %s", "project_damaged": "프로젝트 파일이 손상되었습니다. 원본은 변경되지 않았습니다.", "project_no_schema": "프로젝트에 schema 버전이 없습니다.", "project_no_action": "내장 ActionSpec이 없습니다. 원본 액션을 다시 열고 저장하세요.", "project_action_invalid": "내장 ActionSpec이 유효하지 않습니다. 프로젝트는 변경되지 않았습니다.",
		"project_temp_failed": "임시 프로젝트 파일을 만들 수 없습니다.", "project_replace_failed": "프로젝트를 안전하게 교체하지 못했습니다. 임시 데이터: %s", "asset_unsupported": ".%s 형식은 지원하지 않습니다. PNG, WebP, WAV, OGG, GLB, glTF 또는 Mixamo FBX를 사용하세요.", "asset_not_found": "에셋이 없습니다: %s", "asset_copy_failed": "에셋을 프로젝트에 복사하지 못했습니다.",
		"tutorial": "튜토리얼", "tip_tutorial": "앱 내 튜토리얼과 작업 흐름 도움말 열기", "tutorial_title": "Action Director 튜토리얼 센터", "tutorial_skip": "나중에", "tutorial_close": "닫기", "tutorial_mark_done": "이 장 완료 표시", "tutorial_mark_undone": "미완료로 변경", "tutorial_open_2d": "2D 샘플로 연습", "tutorial_open_3d": "3D 샘플로 연습", "tutorial_progress": "%d / %d장 완료", "manual": "상세 가이드", "tip_manual": "검색 가능한 오프라인 전체 가이드 열기", "manual_title": "Action Director 상세 사용자 가이드", "manual_search": "가이드 검색 (Ctrl/Cmd+F)", "manual_next": "다음 찾기", "manual_found": "찾음", "manual_not_found": "결과 없음",
	},
}

var locale := DEFAULT_LOCALE


func _init(preferred_locale := "") -> void:
	locale = normalize_locale(preferred_locale)


func text(key: String, values: Array = []) -> String:
	var selected: Dictionary = STRINGS.get(locale, STRINGS[DEFAULT_LOCALE])
	var value := String(selected.get(key, STRINGS[DEFAULT_LOCALE].get(key, key)))
	return value % values if not values.is_empty() else value


func set_locale(value: String) -> void:
	locale = normalize_locale(value)


static func normalize_locale(value: String) -> String:
	var normalized := value.replace("-", "_")
	if normalized.begins_with("zh"):
		return "zh_TW"
	if normalized.begins_with("ja"):
		return "ja"
	if normalized.begins_with("ko"):
		return "ko"
	return normalized if normalized in SUPPORTED_LOCALES else DEFAULT_LOCALE
